### ISSUE TITLE
Total rewards numbers are wrong

### ISSUE THREAD

**Issue by avive** [spacemeshos/explorer-frontend#102]
The layer reward on TN 122 is 50 SMH.
This means that about 14,400 SMH should be rewarded in an epoch.
The total rewards in dash and explore for TN 122 seem ~x10 less than that.
You can see here that lots of rewards are not listed: https://stage-explore.spacemesh.io/rewards

**Comment by AndrewAR2** [comment]
The node does not report some of the rewards. For example, the log for layer 604 - only 17 out of 40 rewards were reported.
[epoch-604.log](https://github.com/spacemeshos/explorer-frontend/files/5661212/epoch-604.log)

**Comment by avive** [comment]
Thank you for the log - this is very useful.

**Comment by avive** [comment]
What api stream are you listening to for rewards?

**Comment by avive** [comment]
I'm checking the GlobalState stream and it seems to be sending all rewards for a layer. Is that what you are using?

` grpcurl -d '{"globalStateDataFlags": 2}' -plaintext localhost:9092 spacemesh.v1.GlobalStateService.GlobalStateStream`

**Comment by AndrewAR2** [comment]
We are listening to GlobalStateService.GlobalStateStream

**Comment by avive** [comment]
Yes, there's an issue. See: https://github.com/spacemeshos/go-spacemesh/issues/2228
