### ISSUE TITLE
Epoch's Rewards Screen fixes

### ISSUE THREAD

**Issue by avive** [spacemeshos/explorer-frontend#103]
- Title: `Epoch X - Rewards` -> `Epoch X Rewards`.
- Subtile: `Rewards awarded to Smeshers`. 
- Call-out right-side module: `AWARDS` -> `REWARDS`.

**Comment by Motzart** [comment]
https://stage-explore.spacemesh.io/epochs/4/rewards

**Comment by Motzart** [comment]
fixed

**Comment by avive** [comment]
confirmed.
