### ISSUE TITLE
Incorrect logo in explore and dash

### ISSUE THREAD

**Issue by vomcent** [spacemeshos/explorer-frontend#112]
[stage-dash.spacemesh.io](https://stage-dash.spacemesh.io/) uses an off brand logo lockup, please use linked [SVG](https://www.dropbox.com/s/44gj9nin2d9a5wk/Black%20Lockup%20logo.svg?dl=0).

**Comment by avive** [comment]
Update on both dash and explore front-ends

**Comment by avive** [comment]
@vomcent - you need to provide also the svg for the lite-mode. Best if you can attach here instead of linking to drop box. You can do this on github...

**Comment by vomcent** [comment]
I got a message that GitHub doesn't support SVGs earlier, but here is a zip with both logo lockupss. 
[B+W lockup logos.zip](https://github.com/spacemeshos/explorer-frontend/files/5625185/B%2BW.lockup.logos.zip)

**Comment by Motzart** [comment]
fixed
