### ISSUE TITLE
Status icon color while syncing

### ISSUE THREAD

**Issue by avive** [spacemeshos/explorer-frontend#119]
While the explorer backend is syncing, network status light should be orange and not green. It should only be green when the backend node is synced. Same issue for dash.

**Comment by despablos** [comment]
fixed

**Comment by avive** [comment]
Look at the staging explorer now. The verified layer is stuck but the status color is orange - it should be red...

**Comment by despablos** [comment]
sorry, it's fixed in code, but forgot to update the production version
fixed
