### ISSUE TITLE
Infinite scrolling is not working on tn 122

### ISSUE THREAD

**Issue by avive** [spacemeshos/explorer-frontend#123]
Browse any view that should have lots of data items and scroll down.
Results: you don't see additional data items. Only a fixed number of items.
Expected: see additional auto-scrolled results. 

Pages with this issue on tn 122 explorer:
http://stage-explore.spacemesh.io/accounts
http://stage-explore.spacemesh.io/accounts

**Comment by Motzart** [comment]
Could you provide more info, because i checked it, all work fine, (use chrome)

**Comment by avive** [comment]
Non of the auto-scrolling works for me in chrome.
https://stage-explore.spacemesh.io/accounts
https://stage-explore.spacemesh.io/layers

All of the screens with auto-scrolling return only a small number of results.
Here's the the layers page after I try to scroll down...

<img width="764" alt="Screen Shot 2020-12-09 at 11 19 23 AM" src="https://user-images.githubusercontent.com/96002/101610118-7dd60d80-3a10-11eb-93aa-e8d5c81336eb.png">

**Comment by avive** [comment]
Looks like this is fixed in current deployment

**Comment by despablos** [comment]
fixed
