### ISSUE TITLE
Block Id Display in Block Page

### ISSUE THREAD

**Issue by avive** [spacemeshos/explorer-frontend#126]
- Block ids are 20 bytes (40 hex chars when hex-formatted)
- They are currently come via the api is 30 bytes with the last 10 bytes all 0.
- In block page, the hash field for a block should move to the top of the table from the bottom. Label should be 'Id' and data should be the full 40 hex chars string with 0x prefix. Currently only a prefix of the full id is displayed. e.g:

`Id............ 0x[40hex chars] [copy-button`

**Comment by despablos** [comment]
fixed
