### ISSUE TITLE
Update global frame links and urls

### ISSUE THREAD

**Issue by avive** [spacemeshos/explorer-frontend#127]
1. Replace 2 top links with:
- `Join Testnet`. url: https://spacemesh.io/testnet/
- `Dashboard`. url: https://stage-dash.spacemesh.io/ (until the discovery service is working, when it does - use the same url from the discovery service at https://discover.spacemesh.io/networks.json)
- Clicking on logo should browse `https://spacemesh.io`

2. Use testnet friendly name in drop down instead of devnet - same name as discovery service: `TweedleDee Open Testnet 122`

Automation notes: once explorer is deployed via automation and uses url from discovery service, use information from the discovery service: dash url and network friendly name.

**Comment by despablos** [comment]
fixed

**Comment by avive** [comment]
Looking good but please remove 'community forum' from top links so we only have join testnet and dashboard.

**Comment by despablos** [comment]
fixed

**Comment by avive** [comment]
So now with the discovery service up and running https://discover.spacemesh.io/networks.json
There should not be any hard-coded network id / name in explorer and it should take the following data from the discovery service.

1. If discovery service has more than 1 network then display networks in top-right drop-down - there are the available networks with explore.

There's always a current network that is displayed and user can switch from the top-right menu if there are more than one.
For the current network selected in the drop-down, dashboard link should be updated to display the dashboard for the selected network when clicked.

for now, we only need to support 1 entry in the discovery json file, so the correct behavior now for explore should be:
1. Only the network specified in the json to be displayed in the drop down.
2. Dash link to point to that network's dashboard.
3. All data displayed is for the network.

For example, now that devnet 20 is up and testnet 122 is down - the only network available in the explorer should be devnet 20 and the dashboard link should link to devnet 20 dash.

**Comment by Motzart** [comment]
fixed
