### ISSUE TITLE
Search by layer hash doesn't work

### ISSUE THREAD

**Issue by avive** [spacemeshos/explorer-frontend#135]
1. browse a layer in the explorer and copy its hash.
2. paste in search bar and click search or press enter.

Result: not-found screen.
Expected: display the layer's screen.

**Comment by Motzart** [comment]
actually, search work with layer number, not hash,  should we change it or keep both?

**Comment by avive** [comment]
q: how do you search by layer number? When I input a number in search box it finds the epoch...
Ideally we support both ways to search by layer. Maybe `Layer 2` for layer by number, or just layer hash for layers by hash?

**Comment by avive** [comment]
@Motzart - see question above plz

**Comment by Motzart** [comment]
yep, i saw, i think hash will be better, actually i don't know how Andrey did this, we will do it

**Comment by Motzart** [comment]
@AndrewAR2 could you add search by hash?

**Comment by Motzart** [comment]
done

**Comment by avive** [comment]
confirmed.
