### ISSUE TITLE
No results search page breaks history

### ISSUE THREAD

**Issue by avive** [spacemeshos/explorer-frontend#136]
1. Browse view screens in explore.
2. Search for something that will produce no results.
3. Click back from not-found path

Result: empty screen with this path https://explorer-20.spacemesh.io/not-found

Expected: display the page and url that was in history before the no results page was displayed. This should be the page that the user was at when he clicked search.

4. Click back again. You keep getting other paths with an empty screen e.g. https://explorer-20.spacemesh.io/404

**Comment by avive** [comment]
Is this deployed to devnet 20 explorer? I get an empty page when I search for 0xfff
https://explorer-20.spacemesh.io/not-found/0xff

**Comment by despablos** [comment]
fixed

**Comment by avive** [comment]
confirmed.
