### ISSUE TITLE
Missing Account

### ISSUE THREAD

**Issue by avive** [spacemeshos/explorer-frontend#146]
Account https://explorer-124.spacemesh.io/accounts/0x52ad4e92c8b01e3473c952d5dbae5b808e13ae5e should have a non-zero balance, some rewards and transactions - it is not available in explore. This might be an explore backend-issue or might even be a consensus fork. We need to look into this.

**Comment by avive** [comment]
Here's another account which is in explorer: 
https://explorer-124.spacemesh.io/accounts/0x656A36D868053257a89D3F527cBC7E69E407679c
Try searching for 0x656a36d868053257a89d3f527cbc7e69e407679c
you’ll get account not found

**Comment by Motzart** [comment]
Search form is case insensitive to hex chars

**Comment by avive** [comment]
So the issue is somewhere else.

**Comment by avive** [comment]
https://explorer-124.spacemesh.io/accounts/0x656a36d868053257a89d3f527cbc7e69e407679c is another repro case - account has txs, rewards and a non-zero balance yet I get 'no results' when trying this in my browser.

**Comment by avive** [comment]
This now can be reproduced on live Testnet 128.

1. browse transactions screen.
2. click on any transaction to view it.
3. click on ‘To’ or ‘From’ account 

Result: in many cases you get a no-found screen.

An example.

Transaction: https://explorer.spacemesh.io/txs/0x6e41547b7cb4bbd3a57fca0d8f3e168f1c68c8e7ea1a09cefaa6da17958738f2

Link generated on this screen:
https://explorer.spacemesh.io/accounts/0x029afF2172684D0BeBEc385DFC59c5De0D25d31F

navigation result: https://explorer.spacemesh.io/not-found/0x029afF2172684D0BeBEc385DFC59c5De0D25d31F

**Comment by avive** [comment]
Looks like this is now fixed in deployed 128.
