### ISSUE TITLE
Update network status when verified layer is stuck for a long time

### ISSUE THREAD

**Issue by avive** [spacemeshos/explorer-frontend#148]
When the verified layer doesn't advance in n hours (config param, say set to 24 by default), change the status light to orange from green in both explore and dash frontends and only change it to green back again once verified layer advances.

Currently on TN 124: verified layer has been stuck for ~37 hours but status lights on dash and explore are both green.

https://dash-124.spacemesh.io/

**Comment by Motzart** [comment]
done
