### ISSUE TITLE
Invalidate blocks that are contextually invalid

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/explorer-frontend#149]
Blocks can become INVALID after some number of layers (see the pending change in https://github.com/spacemeshos/api/issues/138). The explorer needs to be able to account for this. Blocks should be displayed with their status (which may be the same as layer status, i.e., PENDING, for some time), until they're finalized as VALID or INVALID. INVALID blocks should be marked invalid, or possibly dropped entirely, along with the transactions they contain.

**Comment by Motzart** [comment]
Ok, @lrettig no problem, how you would like to see this? just add field status to block page or something else ?, maybe icon?

**Comment by lrettig** [comment]
It's a little more complicated than this since it affects not only blocks, but also the transactions they contain.

CC @avive - thoughts?

**Comment by avive** [comment]
Does the api support this? All of this data should come from the api: a block state (which may change at any time) + transaction state (via the receipt data eventually). Explorer backend should be able to handle this but I'm not sure what's the best design as any block or any transaction may change at any time. This whole discussion should move to API repo imo. This is all falls under support mesh reorg and self healing part of the api and explore backend...
