### ISSUE TITLE
Add basic analytics

### ISSUE THREAD

**Issue by avive** [spacemeshos/explorer-frontend#151]
Integrate google analytics so we have basic usage analytics. 
Ping for GA data for integration when you start working on this.

**Comment by avive** [comment]
Copy the global site tag into the <head> section of your HTML. Or, if you use a website builder (e.g. WordPress, Shopify, etc), copy the global site tag into your website builder’s custom HTML field.

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-DC02VE3CP3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-DC02VE3CP3');
</script>
```

**Comment by Motzart** [comment]
done

**Comment by avive** [comment]
confirmed
