### ISSUE TITLE
Rewards ids display

### ISSUE THREAD

**Issue by avive** [spacemeshos/explorer-frontend#156]
Change rewards id display and supported reward url format to include the `0x` prefix. Reward ids currently displayed and are searchable without the suffixes. for example:

https://explorer-28.spacemesh.io/rewards/607ef9a2faf83ac07e63f6c0

All other hex ids are displayed with 0x (or should be) and 0x should appear in the url for pages with hex ids in the url.

**Comment by Motzart** [comment]
actually rewards doesn't have id, this id Andrew get from mongo - this is mongodb id

**Comment by Motzart** [comment]
done
