### ISSUE TITLE
Accounts received amount is always 0

### ISSUE THREAD

**Issue by avive** [spacemeshos/explorer-frontend#159]
1. Go to https://explorer.spacemesh.io/accounts on devnet 207
2. Scroll down to load all accounts.

Result: all received amounts are 0.
Expected: show non-zero received amounts for accounts that have received coins via coin transactions from other accounts. We know these should exist - 934 coin transactions were made at time of reporting...

**Comment by mephistopheles1010** [comment]
Pull request with fix have been created https://github.com/spacemeshos/explorer-backend/pull/12. Waits for approve and merge.
