### ISSUE TITLE
2nd devnet - RED

### ISSUE THREAD

**Issue by Primaveralina** [spacemeshos/explorer-frontend#162]
So we have 2 devnets running so you can see the explore and dash bugs

2nd network from the list in dash - status is RED for long time and explorer link not available at top

**Comment by Primaveralina** [comment]
![2021-12-02 11 32 40](https://user-images.githubusercontent.com/33487597/144395377-84a26707-7e08-48ca-9408-337b2bfce356.jpg)

**Comment by avive** [comment]
Reproducible when there are more than 1 live denvent.

**Comment by avive** [comment]
Is this fixed? We'll handle the actual explorer url as part of the project to properly support more than one devnet.

**Comment by avive** [comment]
@Primaveralina

**Comment by Primaveralina** [comment]
this issue is currently being worked on
@Motzart will comment once done

**Comment by avive** [comment]
I think this is fixed. Can I close?
