### ISSUE TITLE
/rewards should point to proper smesher that is receiving reward when multiple nodes with the same coinbases are in use

### ISSUE THREAD

**Issue by pigmej** [spacemeshos/explorer-frontend#189]
When multiple nodes are using the same coinbase to smesh then this screen https://explorer.spacemesh.io/rewards displays semi-false information and is confusing a lot of people.

After quickly checking, it seems that we have all the needed info INSIDE the go-spacemesh but we might not expose it correctly. (thx @noamnelke for checking)

This issue is meant to track the feature.

**Comment by robandfender** [comment]
it's a bug.

**Comment by kacpersaw** [comment]
Done here: https://github.com/spacemeshos/explorer-backend/pull/94
