### ISSUE TITLE
Account view's Balance link redirects to /rewards instead of /txs

### ISSUE THREAD

**Issue by tjb-altf4** [spacemeshos/explorer-frontend#205]
Currently both Account view's Balance and Rewards link redirect to /rewards.

![image](https://github.com/spacemeshos/explorer-frontend/assets/33798260/7324247f-e903-437f-8b76-c17e0b12b503)

Instead, Balance should redirect to /txs, as per below below.
| link Text | link construction |
| --------- | ------------------ |
| Rewards | explorer.spacemesh.io/accounts/<account_id>/rewards |
| Balance  | explorer.spacemesh.io/accounts/<account_id>/txs |

**Comment by tjb-altf4** [comment]
Actually this is partly incorrect, because of course transactions link will show you transactions *slaps head*
However, as Transactions only shows a count, and not an overall balance like Balance does/should, it is still more suitable to link to /txs rather than /rewards

**Comment by tjb-altf4** [comment]
This issue may be redundant if #203 is implemented

**Comment by kacpersaw** [comment]
#203 was implemented and "Balance" line was removed. Closing.
