### ISSUE TITLE
Improved Loading Behavior/Pagination

### ISSUE THREAD

**Issue by maparr** [spacemeshos/explorer-frontend#207]
## Description
Currently, when scrolling through the [Explorer](https://explorer.spacemesh.io/txs) on the spacemeshos/explorer-frontend, the loading behavior at the end of the page can be confusing for users. It's difficult to determine whether the page is still loading or if it has reached the end of the available data. This can be particularly problematic for users with slower internet connections. 

This feature request proposes an enhancement to the loading behavior and suggests implementing improved pagination to provide a smoother and clearer user experience.

## Proposed Solutions
1. **Delayed Loader**: Introduce a delayed loader that triggers after approximately 300ms if no results are displayed. This will give users a clear indication that the page is still loading and prevent the confusion between loading and reaching the end of the page.

2. **Always Load More**: Implement a continuous loading mechanism where additional data is loaded proactively as the user scrolls. This can be done by pre-loading a couple of pages of data in advance, so users don't encounter an abrupt stop when scrolling to the end.

3. **Normal Pagination**: Consider switching to a standard pagination model where users manually click to load the next page of results. This can provide a more predictable and controlled browsing experience.

## Reproduction Steps
1. Visit the [Explorer](https://explorer.spacemesh.io/txs) page.
2. Begin scrolling down the page to simulate reaching the end.
3. Observe the loading behavior and how it might be unclear whether the page is loading or at its end.

## Acceptance Criteria
1. The loading behavior is enhanced to clearly indicate when the page is still loading data.
2. Users with slower internet connections can easily distinguish between loading and reaching the end of the page.
3. The user experience during scrolling is improved, avoiding abrupt stops and confusion.
4. If pagination is implemented, it functions reliably and intuitively.
5. The solution aligns with the overall design and usability principles of the spacemeshos/explorer-frontend.

This feature request aims to enhance the user experience on the Explorer page by addressing the loading behavior and potentially implementing a more user-friendly pagination mechanism. Your consideration and feedback on this proposal are greatly appreciated.

**Comment by lrettig** [comment]
I ran into this issue today - there's currently no way to view more than the past 40 layers. It doesn't auto-load more and there's no "more" button and no pagination:

![image](https://github.com/spacemeshos/explorer-frontend/assets/3316532/bed262c6-e5df-4ae3-ad0c-6dd21fd4246c)

**Comment by lrettig** [comment]
Strange - now auto load is working for me on the layers page, but it wasn't a few minutes ago
