### ISSUE TITLE
Don't highlight links if it's destination is the same as current page 

### ISSUE THREAD

**Issue by kacpersaw** [spacemeshos/explorer-frontend#237]
## Issue Summary
In the current implementation, links on the page remain highlighted (or contain the link style) even when the user is already on the target page. This can be confusing, particularly when the same link is clicked multiple times, leading to the assumption that it leads somewhere else.

## Example
An example of this issue can be seen on [this page](https://explorer.spacemesh.io/accounts/sm1qqqqqq8a33uxt7834rh78rf97f4tzmeu7g7yefqv5gjzj). Here, attempting to follow the 'FROM' leads to the same page the user is already viewing.

## Expected Behavior
Ideally, the link should not be highlighted or appear as a clickable link when the user is on the same page that the link points to. This will prevent confusion and improve user experience by making it clear that the user is already on the target page.

**Comment by maparr** [comment]
description updated, If it will be hard to resolve, it is possible to make the link visited  ( purple color ). But I hope it is possible to detect the current page and remove it.
