### ISSUE TITLE
Add onHover for some elements for a better clarity

### ISSUE THREAD

**Issue by monikasmolarek** [spacemeshos/explorer-frontend#290]
I will be updating this issue with time adding the elements that would be useful having more explanation (if I find any). 

1. the icons representing the tx status: just a short "applied"/"rejected"/"processing" etc. 
<img width="1033" alt="Screenshot 2024-10-17 at 13 38 14" src="https://github.com/user-attachments/assets/8d439131-8cdc-4d80-95ef-32daa85bb7d1">

2. the summary - Security for sure, indicate for almost all if they are for current epoch or cumulative
<img width="1033" alt="Screenshot 2024-10-17 at 13 51 59" src="https://github.com/user-attachments/assets/58270808-0df0-43b0-a0da-aa056e4eacb9">

3. info it's the count of the transactions for 80 mil (count, not the sum) and the info it's the sum for the rewards value : 
<img width="523" alt="Screenshot 2024-10-17 at 13 57 33" src="https://github.com/user-attachments/assets/57fbff50-37e9-4f66-a427-2beb8bc86c36">

**Comment by kacpersaw** [comment]
> 3. info it's the count of the transactions for 80 mil (count, not the sum) and the info it's the sum for the rewards value :

This block shows that 80 million rewards have been distributed, and the total value of rewards since genesis is 58672163 SMH. 

What do you suggest for the tooltip?

**Comment by monikasmolarek** [comment]
I would suggest smth like this for 80mil :
`This shows the total number of individual rewards distributed. Each reward represents a separate payout made to participants.`

And for the sum: 
`This shows the total combined value of all rewards distributed in SMH. It represents the sum of all individual rewards.`
