### ISSUE TITLE
Design Review

### ISSUE THREAD

**Issue by avive** [spacemeshos/explorer-frontend#35]
# General comments

- Wrong dark gray color used for some text not readable. e.g. transaction page, account page. Change that text style to white when in dark-mode. See ref mock in Figma.
- In all places we display UTC times should be rendered in the user's local time-zone. e.g. 10:33:6 + UTC => 1:54pm (local time zone code). Also remove the `+` char between time and time zone code. e.g `10:53:16 + UTC` -> `10:43:16 UTC`.
- Change text in age label from `few secs ago` to `just now`.
- Epoch and label age should be their start time which can't be in the future - it should always be 'just now' or 'x seconds ago...'.
- There is an issue with all routes - when viewing a sub-page of an entity, e.g. epoch's rewards, epoch's transactions the route should be /epoch/xxxx/rewards, /epoch/xxxx/layers and not `/epochs/566/rewards`. Needs to be fixed for all routes - see shared doc for reference of requested path syntax...
- Callout area (top-right module) - in some cases the label is light-gray, in some white (in dark mode) - always display label in white (dark-mode) (like in overview page).
- We need to set a short descriptive page title for each of the routes. Currently page title is `Spacemesh Explorer` for all pages. For example, transactions detail page title should be `Transaction Details`.
- All hex ids short strings should be in this format: `0x1234...5678` for consistency.
- Columns that display a number of an amount in table views should be right-aligned. For example, here: http://stage-explore.spacemesh.io/txs - the data in the `value` column is wrongly center-aligned.
----

# Start page
- [x] Data in mini dashboard should be linked to the appropriate page, e.g. accounts, epoch, layer, smeshers....
- [x] Title should be `Transactions` and not `Latest Transaction`. Subtitle: `Recent transactions`.
- [x] Search bar: add spaces around `/` chars in placeholder text.
- [x] `Browse all` link - wrong color in dark mode - please look at Figma mock - should be white...
- [x] `Total TXS value since genesis: 0.3 SMH` -> `Coin transferred: 0.3 SMHH`. We will add help tooltips with more detailed explanation to figure but we want to keep them very short for now.
---

# Transactions Page
- [x] Callout. Main data item label: `Since Genesis`. It is obvious these are transactions. Right-most column: `Value Since Genesis: 0.028 SMH`. No need to state 'total txns'.

---
# Transaction Page
- [x] dark mode - data is not readable due to being light-gray on dark gray. Make dark-gray text white so it is high contrast against the black background. It is the same issue on other pages such as a layer page - check the ref mocks in figma. The dark gray text color needs to be changed to white.
- [x] Title label: `Transaction Details`. Subtitle: `0x1234...6789`.
- [x] Timestamp: add space char after `ago` and `(`.
- [x] Fee is always displayed 0 - should be taken from the tx object - user provider fee in smidge units.
- [x] Page url should be /tx/xxx and not /txs/xxx.
- [x] The `coin` and `sent` small labels in the call-out area should be aligned to the top and bottom of the text (see figma mocks).
---

# Layers Page
- [x] Change column header from `Age` to `Started` (to be consistent with other pages such as epochs).
- [ ] Age/Started data should be layer start time and not end time (same for epochs). Also applicable to the call-out module (top-right). It should display the last known layer start time.
- [x] `ATX VALUE` -> 'ATX'.
- [x] Replace 'Started' and 'Transactions' column.
- [x] Unify Transactions and TXN Value column into one with this data formatting: `[num_of_txs] [smh_value]`. e.g. `10 Transactions (32.302 SMH)`.
- [x] Call-out right-most column. Change to these 3 lines: `Most Recent layer\n date\n \nage` - no need for time stamp here. It is not clear what the data is without this label.

-----

# Epochs Page
- [x] `Total SMC` -> `Value`.
- [x] Add a bit more left space in layout for the `value` column. It is too close to the rewards data column on its left.
- [x] We need to clarify that the time in the call-out is time since genesis. Add label `Genesis Time`. Remove detailed time-stamp and only keep date and age. e.g. 3 lines of text should be: `Genesis Time\n 8/21/2020\n 9 days ago`.
- [x] Callout area. `Epochs` -> `Epochs since genesis` and make the label white like in the overview screen (dark mode reviewed).

----

# Layer Page
- [x] Blue title: `Layer 1278`. Subtitle white: `Layer details`.
- [x] Times: let's please unify on the same age formatting we discussed. e.g.
- [x] Remove 'Layer' from the text of the top 3 row. It is obvious that these are layer properties.
- [x] `Finality` -> `Confidence`. For now there should be only 2 possible values `Confirmed` or `Pending`. Confirmed is for any layer that was verified. Pending is for layers which have not been verified yet.
- [x] Blocks row: `22 blocks` -> `22` - it is obvious these are blocks and this is more consistent with other rows.
- [ ] Page url should be `/layer/xxx` and not `/layers/xxx`.
- [x] `Total Rewards` -> `Rewards`.
- [x] `Total Transactions` ->  `Transactions`.
- [x] In top-right call-out area: `TOTAL COIN REWARDS: 35.417 SMH` -> `Rewards 35.417 SMH` - in 2 lines.
- [ ] Age should be based on the layer's start time and not its end time. So, current layer age will always be ago and not from now in the future...

 ---

# Layer Transactions Page
- [ ] Change route (url) from `/layers/xxx/txs` to /layer/xxxx/txs`
- [x] Title: `Layer XXX Transactions`. Subtitle: empty.
- [x] Call-out module: `Total TXNS value: 0 SMH` -> `Transactions Value: 0 SMH`

---

# Accounts Page
- [x] Call-out on right side: 'accnts' -> 'Accounts' and make label white - it is light grey in dark-mode.
- [x] Call-out right-most column: `Most Recent Account \n data\n age\n` - no need for time-stamp and needs a label as it is not clear what the data is without one.

--
# Account Page
- [x] Title: 'Account'. Subtitle: `Coin account` (for simple coin accounts)
- [x] Title for address row should be 'Address' and not 'Account'.
- [x] Add `Balance` row. Some users may miss the call-out amount.

---

# Account Transactions Page
- [x] Title: `Account Transactions`. Subtitle: `0x1234...1234` (account address). The address displayed is not the account's address. See: http://stage-explore.spacemesh.io/address/0xa7A424f4A77Bfd4b72EC5a68214ac8f3Da849236/txs - looks like it is hard-coded.
- [ ] Add transaction timestamp to each row. e.g. `3 days ago`. Not sure how we missed this :-) -
- [x] Not clear what is the timestamp that is displayed on the top-right call-out. It should be the time of the last transaction but it is not. see: http://stage-explore.spacemesh.io/address/0xa7A424f4A77Bfd4b72EC5a68214ac8f3Da849236/txs

----

# EPOCH Page
- [x] title: `Epoch XXX - DETAILS` -> `Epoch XXX`. Sub-tile: `Epoch details`.
- [ ] Route (url): `epochs/xxx` -> `epoch/xxx`.
- [x] Update labels: `Epoch Number` -> `Number`, `Total Layers` -> `Layers`. `Total Rewards number` -> `Rewards`. `Total Rewards value` -> `Rewards Amount`.

----

# EPOCH transactions page
- [ ] Route (url): `epochs/xxx` -> `epoch/xxx`

# EPOCH layers page
- [ ] Route (url): `epochs/xxx/layers` -> `epoch/xxx/layer` (see routes table in g doc spec).

----

# Search Bar
- [x] When entering something there are no results for, hide the empty details area (id..., type...).

-----------

# Rewards Page
- [x] Title: `All Mining Rewards` -> `Smeshing Rewards`. Don't use mining anywhere - just smeshing.
- [x] Add a bit space between the rewards distributed number and the label - they are too close together.
- [x] `Smesh rewards since genesis` -> `Rewards value since genesis`.
- [x] `Rewards` column label -> `Reward`.
----

# Reward Page
- [x] Title: `Reward 0x1235...4567`. Subtitle: 'Details'.
- [x] `Layer Number` -> `Layer`.
- [x] `Smesher ID` -> `Smesher Id`.

-----

# Smeshers Page
- [x] Use new smesher color (non-black) so 2 top modules are readable.
- [x] `Committed Space` -> `Space`.
- [x] `ID` -> `Smesher Id`.
- [x] `Total ATX TXNS` -> `Activations`.
- [x] Subtitle: make it empty for now.
- [ ] call-out, right-most column: display total space committed by all Smeshers. e.g. `Total Space\n [total_space]`.
----

# Smesher Page
- [ ] Url should be /smesher/0x... and not /smeshers/0x...
- [x] Use the new smesher color (non-black).
- [x] `Reward Committed` -> `Rewards`.
- [x] `Total Transactions` -> `Activations`.
- [x] Title: 'Smesher 0x1234...5678'. Subtitle: 'Details'.
----

# ATXs Page
- [x] Use ATX color for top modules and not black.
- [x] Title: `Smesher 0x1345..6789 Activations`. Subtitle: empty string for now.
- [x] `atxns` -> `Activations` in right-side module.
- [x] `PREVATX` -> 'Previous Activation'.

----

# ATX Page
- [x] Use ATX color and not coin-transaction color.
- [x] Title: `Activation 0x1234...5678`.
- [x] `Id` -> `Activation Id`.
- [x] Remove block row for now.
- [x] `Previous ATX` -> `Previous Activation`.
- [x] Label 'sent' in call-out area should not be displayed for an atx.
- [x] Align label 'atx' in callout area to text baseline (bottom).
----

# VAULT Page
- [ ] Url should be /app/.. and not /apps/...
- [x] Title: `Smart Wallet...` -> `Vault [vault_name]`. Subtitle: `A vault app`.
- [x] Hide `State Hash` row.
- [x] `Daily Spend Address` -> `Daily Spend Account`.
- [x] `Authorized Accounts` -> `Master Accounts`. Value for that is 1 or 3 clickable addresses.
- [x] Add row `Monthly Vested Amount` and value is a SMH value.

---

**Comment by avive** [comment]
This is marked as fixed but I still see `0` in tx page. For example: https://stage-explore.spacemesh.io/txs/0xe1dffd47c453d88bb5f8f9891cc3d77b98c7c75bfe56bbd9de6beb2de3e0fb19
- [+] Fee is always displayed 0 - should be taken from the tx object - user provider fee in smidge units.

**Comment by avive** [comment]
I still see the UTC time in the epochs screen and not the data, per this item (marked as fixed):

- [ ] We need to clarify that the time in the call-out is time since genesis. Add label Genesis Time. Remove detailed time-stamp and only keep date and age. e.g. 3 lines of text should be: Genesis Time\n 8/21/2020\n 9 days ago.

**Comment by avive** [comment]
Typo in subtitle: `Layers details` -> `Layer details` per this issue:

- [ ] Blue title: Layer 1278. Subtitle white: Layer details.

**Comment by avive** [comment]
Regarding this issue:
- [ ] Call-out right-most column: Most Recent Account \n data\n age\n - no need for time-stamp and needs a label as it is not clear what the data is without one.

2nd line should be date - e.g day_of_month/month/year and not time stamp. I meant `date` in the comment and not `data`.

**Comment by avive** [comment]
Regarding:

- [ ] Not clear what is the timestamp that is displayed on the top-right call-out. It should be the time of the last transaction but it is not. see: http://stage-explore.spacemesh.io/address/0xa7A424f4A77Bfd4b72EC5a68214ac8f3Da849236/txs .
Let's make it display like this:

Most Recent Transaction
8/22/2020
16 Days Ago

**Comment by avive** [comment]
Regarding: 
- [ ]  Reward Committed -> Rewards.

Label is currently `Reward` - please change to `Rewards`.

**Comment by avive** [comment]
Regarding:
- [ ] Title: Smart Wallet... -> Vault [vault_name]. Subtitle: A vault app.

For a vault page. Subtitle is still `A smart wallet app`. Should be 'A vault app`.

**Comment by avive** [comment]
@Primaveralina - making sure you saw the issues here in my comments....

**Comment by avive** [comment]
@Motzart - did you see my comments here on some of the fixes?

**Comment by Motzart** [comment]
> Regarding:
> 
> * [x]  Title: Smart Wallet... -> Vault [vault_name]. Subtitle: A vault app.
> 
> For a vault page. Subtitle is still `A smart wallet app`. Should be 'A vault app`.

Fix

**Comment by Motzart** [comment]
> Regarding:
> 
> * [x]   Reward Committed -> Rewards.
> 
> Label is currently `Reward` - please change to `Rewards`.

Fix

**Comment by Motzart** [comment]
> I still see the UTC time in the epochs screen and not the data, per this item (marked as fixed):
> 
> * [x]  We need to clarify that the time in the call-out is time since genesis. Add label Genesis Time. Remove detailed time-stamp and only keep date and age. e.g. 3 lines of text should be: Genesis Time\n 8/21/2020\n 9 days ago.

Fix

**Comment by Motzart** [comment]
> This is marked as fixed but I still see `0` in tx page. For example: https://stage-explore.spacemesh.io/txs/0xe1dffd47c453d88bb5f8f9891cc3d77b98c7c75bfe56bbd9de6beb2de3e0fb19
> 
> * [x]  Fee is always displayed 0 - should be taken from the tx object - user provider fee in smidge units.

We get fee from back, it is equal 0

**Comment by Motzart** [comment]
> Regarding this issue:
> 
> * [x]  Call-out right-most column: Most Recent Account \n data\n age\n - no need for time-stamp and needs a label as it is not clear what the data is without one.
> 
> 2nd line should be date - e.g day_of_month/month/year and not time stamp. I meant `date` in the comment and not `data`.
> Also, first line `Most Recent Account` needs to appear in the first line. So we have:
> 
> Most Recent Account
> 8/21/2020
> 16 Days Ago

fix

**Comment by avive** [comment]
> > This is marked as fixed but I still see `0` in tx page. For example: https://stage-explore.spacemesh.io/txs/0xe1dffd47c453d88bb5f8f9891cc3d77b98c7c75bfe56bbd9de6beb2de3e0fb19
> > 
> > * [x]   Fee is always displayed 0 - should be taken from the tx object - user provider fee in smidge units.
> 
> We get fee from back, it is equal 0

@lrettig - is this an API bug or a misunderstanding between API and backends? Currently all transactions show 0 fee. How can we address this?

**Comment by avive** [comment]
> > I still see the UTC time in the epochs screen and not the data, per this item (marked as fixed):
> > 
> > * [x]   We need to clarify that the time in the call-out is time since genesis. Add label Genesis Time. Remove detailed time-stamp and only keep date and age. e.g. 3 lines of text should be: Genesis Time\n 8/21/2020\n 9 days ago.
> 
> Fix

In the 119 explorer - I still see UTC formatted time in epoch screen, layer screen, tx screen, rewards screen. All dates should be displayed in user's (browser) local time.

**Comment by lrettig** [comment]
> > > This is marked as fixed but I still see `0` in tx page. For example: https://stage-explore.spacemesh.io/txs/0xe1dffd47c453d88bb5f8f9891cc3d77b98c7c75bfe56bbd9de6beb2de3e0fb19
> > > 
> > > * [x]    Fee is always displayed 0 - should be taken from the tx object - user provider fee in smidge units.
> > 
> > 
> > We get fee from back, it is equal 0
> 
> @lrettig - is this an API bug or a misunderstanding between API and backends? Currently all transactions show 0 fee. How can we address this?

Which endpoint is being used to read this? Tx returned by TransactionService/MeshService does not include a "fee" field because there is no "fee" data stored on mesh. On mesh, we store the _gas offered_ by a tx, which includes max gas (`gas_provided`) and gas price (not currently implemented). See https://github.com/spacemeshos/api/blob/a2af5cc13c7c112d996848b85219499ba0cbc233/proto/spacemesh/v1/types.proto#L34.

To see gas actually used/fee paid, you'd have to look at the `TransactionReceipt` which IIRC is not currently implemented either: https://github.com/spacemeshos/api/blob/a2af5cc13c7c112d996848b85219499ba0cbc233/proto/spacemesh/v1/global_state_types.proto#L53 and see https://github.com/spacemeshos/go-spacemesh/issues/2072

**Comment by Motzart** [comment]
> > > I still see the UTC time in the epochs screen and not the data, per this item (marked as fixed):
> > > 
> > > * [x]    We need to clarify that the time in the call-out is time since genesis. Add label Genesis Time. Remove detailed time-stamp and only keep date and age. e.g. 3 lines of text should be: Genesis Time\n 8/21/2020\n 9 days ago.
> > 
> > 
> > Fix
> 
> In the 119 explorer - I still see UTC formatted time in epoch screen, layer screen, tx screen, rewards screen. All dates should be displayed in user's (browser) local time.

Sorry, maybe i misunderstood, but all time in app use localtime ( time from browser ), maybe problem in label 'UTC', i removed it

**Comment by Motzart** [comment]
> > > > This is marked as fixed but I still see `0` in tx page. For example: https://stage-explore.spacemesh.io/txs/0xe1dffd47c453d88bb5f8f9891cc3d77b98c7c75bfe56bbd9de6beb2de3e0fb19
> > > > 
> > > > * [x]     Fee is always displayed 0 - should be taken from the tx object - user provider fee in smidge units.
> > > 
> > > 
> > > We get fee from back, it is equal 0
> > 
> > 
> > @lrettig - is this an API bug or a misunderstanding between API and backends? Currently all transactions show 0 fee. How can we address this?
> 
> Which endpoint is being used to read this? Tx returned by TransactionService/MeshService does not include a "fee" field because there is no "fee" data stored on mesh. On mesh, we store the _gas offered_ by a tx, which includes max gas (`gas_provided`) and gas price (not currently implemented). See https://github.com/spacemeshos/api/blob/a2af5cc13c7c112d996848b85219499ba0cbc233/proto/spacemesh/v1/types.proto#L34.
> 
> To see gas actually used/fee paid, you'd have to look at the `TransactionReceipt` which IIRC is not currently implemented either: https://github.com/spacemeshos/api/blob/a2af5cc13c7c112d996848b85219499ba0cbc233/proto/spacemesh/v1/global_state_types.proto#L53 and see [spacemeshos/go-spacemesh#2072](https://github.com/spacemeshos/go-spacemesh/issues/2072)

@avive @lrettig so, judging from @lrettig  comments we will have to wait until the necessary params are being implemented. right?

**Comment by avive** [comment]
I think that in the short-term the gas_provided smidge amount from the transaction should be displayed for simple coin transactions as this amount is always paid by the user. Longer term, this data should come from the tx receipt.

**Comment by avive** [comment]
I'm going to move any issue I see is not fixed yet to a new issue and close this mega issue.
