### ISSUE TITLE
Network status indicator

### ISSUE THREAD

**Issue by avive** [spacemeshos/explorer-frontend#36]
- Add network status traffic light indicator on the left of the network name in the top-right side drop-down.
- Mock: https://www.figma.com/file/Eiard6VrRc9QZhF5oRG8W5/Explore-Dash-May-2020-Edition?node-id=5201%3A4856

**Comment by Motzart** [comment]
explorer-frontend doesn't have network name, could you provide more information where it should be?, Mock - it's dashboard

**Comment by avive** [comment]
Sorry, wrong mock. Here is the correct one: https://www.figma.com/file/Eiard6VrRc9QZhF5oRG8W5/Explore-Dash-May-2020-Edition?node-id=4586%3A11028 - so the status light should be on the top-right side, in the drop-down.

<img width="502" alt="Screen Shot 2020-10-18 at 9 32 00 PM" src="https://user-images.githubusercontent.com/96002/96376733-63f31980-1189-11eb-9ddd-aedd4a707d7e.png">

We are going to have a friendly name for every spacemesh network in the net config file next to its net id.

**Comment by avive** [comment]
Confirmed
