### ISSUE TITLE
Update entities colors

### ISSUE THREAD

**Issue by avive** [spacemeshos/explorer-frontend#37]
- Smesher - #5C09AF (from black)
- Activation - #F7D353 (from same color as tx)

**Comment by Motzart** [comment]
done

**Comment by avive** [comment]
I'm not sure if you deployed to https://stage-explore.spacemesh.io/smeshers - but the background of the right side module is wrong - it should be the entity color... also here: https://stage-explore.spacemesh.io/smeshers/0x022d584db76c7b0b5f4df94883a08566ee40a428bc199cb5ced115e27e0ec476

If you push a fix to develop best is to update the deployment so we can review the fixes.

**Comment by avive** [comment]
Clarification: we have a color for each main entity and we use it in its screens. e.g layer is blue, tx is green - see the google shared doc spec plz for more info.

**Comment by avive** [comment]
Layer - BLUE #1776E3
Transaction - GREEN #65B042
Reward - #24AEA6
Epoch - Orange   #F79F53
Account - #DF32AF
Smesher  - BLACK #252429 
Block -  Dark blue #1744E3
Smart Wallet - Dark Red  #DF3266

**Comment by avive** [comment]
Smeshers right-side module background color is bad. See:

<img width="1267" alt="Screen Shot 2020-10-11 at 11 18 03 AM" src="https://user-images.githubusercontent.com/96002/95673679-7e3e5d80-0bb3-11eb-8103-0c08531534bd.png">

**Comment by Motzart** [comment]
color has been updated, but we need background color for Activation and Smesher

**Comment by avive** [comment]
@vomcent please provide background colors spec for activations and smeshers. The darker shade of the entity color - similar to what we have in the mocks for other entities such as transactions.

**Comment by vomcent** [comment]
hey! smasher bg is #4F4731 and atx is #301F44. for future reference the background darker shade is just the result of taking the main color at 20% opacity over the dark grey bg color.

**Comment by Motzart** [comment]
fix

**Comment by avive** [comment]
What I see in explorer now is both activations and smeshers using the activations color - they should each have their own color...

**Comment by Motzart** [comment]
ok, my opinion - https://stage-explore.spacemesh.io/smeshers/0x02b968108db1f9c58a2fadd8c5a7d16c83f931b2357ac9f3f63ba49c21b2ecae/atxs - this is smesher page(because main page is smesher) and should use smesher colors, but this is activation page and should use activation colors https://stage-explore.spacemesh.io/atxs/0xa5f7196dd36fa634e3d3d4e3fef7f46259552ac0c8c612a7f765880ffdb287c5, 
correct me please, if I'm wrong @avive

**Comment by avive** [comment]
You are correct.
@vomcent - please have a look at the activation color: https://stage-explore.spacemesh.io/atxs/0x01d74e41c9be232bf146322a78843769dba10fdfa3e12305b09ec44d13efe9c1
The dark purple doesn't look good over the black background... more contrast is needed

![Uploading Screen Shot 2020-10-27 at 2.51.40 PM.png…]()

**Comment by avive** [comment]
Please update the activations color to this:
New purple: #7B42F4
Dark purple bg: #362A52
light purple bg: #DBD0F3

Please update the yellow entity with these colors:

New Yellow: #F7D353
Dark Yellow BG: #4F4731
Light Yellow BG: #F4EDD3

**Comment by Motzart** [comment]
fix

**Comment by avive** [comment]
confirmed.
