### ISSUE TITLE
Smeshers page call-out module

### ISSUE THREAD

**Issue by avive** [spacemeshos/explorer-frontend#48]
In dark mode, the callout background color is wrong. It should be the smeshers color. It is currently light gray and the text is not readable. See: https://stage-explore.spacemesh.io/smeshers . Same issue in Smesher screen. See: https://stage-explore.spacemesh.io/smeshers/0x022d584db76c7b0b5f4df94883a08566ee40a428bc199cb5ced115e27e0ec476

**Comment by Motzart** [comment]
fix

**Comment by avive** [comment]
It is still using wrong color. There's another open issue about that background color. I've attached a screen shot to the other issue. In current explorer deployment, background is white in dark mode.

**Comment by Motzart** [comment]
fix

**Comment by avive** [comment]
Confirmed.
