### ISSUE TITLE
Vault page master accounts

### ISSUE THREAD

**Issue by avive** [spacemeshos/explorer-frontend#50]
For now, please hack 3 standard spacemesh addresses for this row. Use the short format for each address. Eg. 0x1234...1234. Currently a Smesh amount is displayed for that row. Ref: https://stage-explore.spacemesh.io/apps/0x69c756d06F0C1236F34D3A627EAcb7a4722FC5B8

**Comment by Motzart** [comment]
Fix

**Comment by avive** [comment]
I can't verify more fixes without a live explorer with some data. @Motzart @Primaveralina - so guys, the sooner you bring one up the better....

**Comment by Primaveralina** [comment]
@avive Explorer BE will be ready in the evening. I'll update you once done.

**Comment by avive** [comment]
It is okay for now. We need to implement all vault features in next dev iteration.
