### ISSUE TITLE
Timestamp formatting

### ISSUE THREAD

**Issue by avive** [spacemeshos/explorer-frontend#51]
- In call-out modules (right-side) use a simple date format and don't display a timestamp. e.g. 05/10/2020.
- When displaying a time-stamp, remove the `+` char from the format so we get: `13:29:46 UTC`.
- Display the timestamps in the user's local-time zone and not in UTC.

**Comment by Motzart** [comment]
done

**Comment by avive** [comment]
Please also apply display in user's local time zone in all places where a UTC date is displayed. 
For example, layer page, epoch page, etc...

**Comment by avive** [comment]
On some pages there's a missing space between `ago` and `(`). For example: https://stage-explore.spacemesh.io/layers/9039

**Comment by avive** [comment]
Opening so we can close when the 2 mentioned issues are fixed.

**Comment by Motzart** [comment]
fix

**Comment by avive** [comment]
Maybe the staging explorer is not up-to-date with the latest fixes but it is easy to find places where UTC formatting is still used:
https://stage-explore.spacemesh.io/rewards/5f6d843d02ea937924688fd7
`month ago (Sep/21/2020 17:09:46 UTC)`

**Comment by avive** [comment]
For example, transaction details screen - timestamp UTC formatted:
https://stage-explore.spacemesh.io/txs/0x6c610f1f274ec0d0206520ba1d7f947f110cb66ad8eac4ef095165e9207ee060

**Comment by avive** [comment]
Looks like this if fixed - nice job!
