### ISSUE TITLE
Remove colon char in transactions screen

### ISSUE THREAD

**Issue by avive** [spacemeshos/explorer-frontend#57]
https://stage-explore.spacemesh.io/txs
https://stage-explore.spacemesh.io/rewards

In right-side call-out module - remove `:` char between label and value to be consistent with all other callouts. There are few screen where colon is displayed and in most it doesn't. Shared 2 screen I could find above.

**Comment by Motzart** [comment]
Fix

**Comment by avive** [comment]
Confirmed.
