### ISSUE TITLE
Rewards screen sorting

### ISSUE THREAD

**Issue by avive** [spacemeshos/explorer-frontend#73]
Rewards should be sorted by the layer # where the most recent layer rewards are displayed first.
https://stage-explore.spacemesh.io/rewards

Right now, rewards from newer layer are sometime displayed below rewards for older layers:

<img width="1035" alt="Screen Shot 2020-10-28 at 2 04 15 PM" src="https://user-images.githubusercontent.com/96002/97433651-8540cc00-1926-11eb-886b-c335521e51bc.png">

**Comment by Motzart** [comment]
fixed

**Comment by avive** [comment]
Confirmed.
