### ISSUE TITLE
Smesher Rewards Sorting

### ISSUE THREAD

**Issue by avive** [spacemeshos/explorer-frontend#74]
Please sort smesher's rewards by reward layer descending. Currently, rewards for older layer appear before rewards for newer ones. See: https://stage-explore.spacemesh.io/smeshers/0x02b968108db1f9c58a2fadd8c5a7d16c83f931b2357ac9f3f63ba49c21b2ecae/rewards

**Comment by Motzart** [comment]
fix

**Comment by avive** [comment]
Confirmed.
