### ISSUE TITLE
Address Security Advisories

### ISSUE THREAD

**Issue by avive** [spacemeshos/explorer-frontend#86]
Update 3rd party deps to address security advisories from github.

**Comment by Motzart** [comment]
Is it relevant? if yes could you provide more info ?

**Comment by avive** [comment]
https://github.com/spacemeshos/explorer-frontend/network/alerts

**Comment by Motzart** [comment]
this link doesn't work ;(( 404

**Comment by avive** [comment]
Please try again - it must be a repo permissions issue.
When I browse the repo I get a callout with this issue: `We found potential security vulnerabilities in your dependencies.
You can see this message because you have been granted access to Dependabot alerts for this repository.`

**Comment by Motzart** [comment]
cool, now i see, i'll fix it all

**Comment by Motzart** [comment]
fixed
