### ISSUE TITLE
Vaults icon

### ISSUE THREAD

**Issue by avive** [spacemeshos/explorer-frontend#87]
Current look - using account icon:

<img width="325" alt="Screen Shot 2020-11-12 at 8 10 38 AM" src="https://user-images.githubusercontent.com/96002/98902547-9826d500-24be-11eb-8167-f8593ef43db1.png">

Expected: Use vault icon.

@vomcent - do we have the art for it?

**Comment by vomcent** [comment]
[SVG here](https://www.dropbox.com/s/v9hogt5j7vy4ue1/vault%20explorer%20icon.svg?dl=0), figma reference [here](https://www.figma.com/file/B9U2mTqpbInL9ATdOuDdPR/Explore-Dash-May-2020-Edition-BACKUP?node-id=5231%3A9319). Just for reference I didn't have editing access to the up to date explorer file, so this is an old version I edited just now.

**Comment by Motzart** [comment]
fixed

**Comment by avive** [comment]
confrimed
