### ISSUE TITLE
Layer's blocks page review

### ISSUE THREAD

**Issue by avive** [spacemeshos/explorer-frontend#96]
- Title: `Layer xxxx Blocks`.
- Subtitle: empty.
- right-side callout: `layer blocks` -> `blocks`.
- Smesher id should be displayed - it is the id of the smesher who submitted that block. Currently `--`. Should be link to open the smesher's screen. Explore should have this data.
- `TXN value` -> `Value`.
- Replace age and transactions column.
- Remove all trailing 0s from block ids (also see #95). `0x58163b6e2fed2130bbbeabb2f3a4e99202d5ac3e000000000000000000000000` -> `0x58163b6e2fed2130bbbeabb2f3a4e99202d5ac3e`

**Comment by Motzart** [comment]
@despablos - 0x58163b6e2fed2130bbbeabb2f3a4e99202d5ac3e000000000000000000000000 - this is from back, let @AndrewAR2  know about this

**Comment by AndrewAR2** [comment]
> Smesher id should be displayed - it is the id of the smesher who submitted that block. Currently --. Should be link to open the smesher's screen. Explore should have this data.

The node API has no information about which smesher submitted this block.

**Comment by avive** [comment]
We need to add ATX ID to the block data returned by the mesh api.

**Comment by lrettig** [comment]
See https://github.com/spacemeshos/api/issues/113

**Comment by despablos** [comment]
Fixed all, except:
- Smesher id should be displayed - it is the id of the smesher who submitted that block. Currently --. Should be link to open the smesher's screen. Explore should have this data;
- Remove all trailing 0s from block ids (also see #95). 0x58163b6e2fed2130bbbeabb2f3a4e99202d5ac3e000000000000000000000000 -> 0x58163b6e2fed2130bbbeabb2f3a4e99202d5ac3e ;

**Comment by avive** [comment]
Please replace the 'age' and 'transactions' table headers order. Looks like only the data columns order was replaced.

**Comment by Motzart** [comment]
fixed

**Comment by avive** [comment]
Nice job on the fixes. I'm closing this issue as most issues were fixed. Going to open a new one about linking from block to smesher and to activation as soon as the api supports these.
